# Generated by Django 5.1.3 on 2024-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_number',
            field=models.CharField(default=1770395349, max_length=16),
        ),
    ]
