# Generated by Django 5.1.3 on 2024-12-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_jobposition_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_number',
            field=models.CharField(default=407317494, max_length=16),
        ),
    ]
