# Generated by Django 5.1.3 on 2025-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_jobposition_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_number',
            field=models.CharField(default=2196131732, max_length=16),
        ),
    ]
