# Generated by Django 5.1.3 on 2025-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_jobposition_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_number',
            field=models.CharField(default=8639260990, max_length=16),
        ),
    ]
