# Generated by Django 5.1.3 on 2024-12-01 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(default=1053931820, max_length=16)),
                ('owner_name', models.CharField(max_length=30)),
                ('desigination', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/system/ownership')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ownership',
                'verbose_name_plural': 'Ownership',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('tag_line', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/system/logo')),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('tel_number', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('working_hours', models.TextField(blank=True, max_length=255, null=True)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('date_established', models.DateField(blank=True, null=True)),
                ('ownership', models.ManyToManyField(to='system.ownership')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.organization')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
