# Generated by Django 5.1.3 on 2025-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=5015254947, max_length=16),
        ),
    ]
