# Generated by Django 5.1.3 on 2024-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=2031994943, max_length=16),
        ),
    ]
