# Generated by Django 5.1.3 on 2025-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_ownership_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=9804039472, max_length=16),
        ),
    ]
