# Generated by Django 5.1.3 on 2024-12-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_ownership_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=1245300765, max_length=16),
        ),
    ]
