# Generated by Django 5.1.3 on 2024-12-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_ownership_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=724200078, max_length=16),
        ),
    ]
