# Generated by Django 5.1.3 on 2024-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_ownership_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=2933845636, max_length=16),
        ),
    ]
