# Generated by Django 5.1.3 on 2025-02-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_ownership_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.CharField(default=8537803917, max_length=16),
        ),
    ]
