# Generated by Django 5.1.3 on 2025-03-01 05:32

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='0801389513801030', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
