# Generated by Django 5.1.3 on 2024-12-01 00:46

import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='middle_name',
            field=utils.validators.TitleCaseField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='3379970364301021', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
