# Generated by Django 5.1.3 on 2025-03-01 05:47

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_staffuser_username_alter_staff_staff_id_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-joining_date'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='2517593464801030', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['email'], name='staff_staff_email_idx'),
        ),
    ]
