# Generated by Django 5.1.3 on 2025-03-01 05:50

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_staff_options_alter_staff_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='2515975105801030', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
