# Generated by Django 5.1.3 on 2025-03-04 12:50

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_staff_email_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='weekend_clossing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='weekend_openning_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='4743819305514030', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
