# Generated by Django 5.1.3 on 2024-12-09 12:07

import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='5512852570519021', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
