# Generated by Django 5.1.3 on 2025-03-07 13:05

import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_workplace_weekend_clossing_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='work_place',
            new_name='workplace',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='1907392050617030', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
