# Generated by Django 5.1.3 on 2025-03-10 15:58

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_work_place_staff_workplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='acccess_card',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='education_level',
            field=utils.validators.TitleCaseField(choices=[('Other', 'Default'), ('Certificate', 'Certificate'), ('High School', 'High School'), ('College', 'College'), ('Diploma', 'Diploma'), ('Bachelors', 'Bachelor'), ('degree', 'Degree'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate')], default='Other', max_length=14),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='1895900185810130', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=utils.validators.TitleCaseField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('On Hold', 'On Hold'), ('Resigned', 'Resigned'), ('Retired', 'Retired'), ('On Leave', 'On Leave'), ('Dismissed', 'Dismissed')], default='Active', max_length=20),
        ),
    ]
