# Generated by Django 5.1.3 on 2025-02-27 06:10

import utils.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_staff_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=utils.validators.TitleCaseField(default='9253585301907220', max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
