# Generated by Django 5.1.3 on 2024-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(default='3635180364', max_length=16),
        ),
        migrations.AlterField(
            model_name='formdocument',
            name='form_id',
            field=models.CharField(default='3635180364', max_length=10, primary_key=True, serialize=False, verbose_name='Form ID'),
        ),
        migrations.AlterField(
            model_name='transmital',
            name='transmital_id',
            field=models.CharField(default='652618036430', max_length=16, primary_key=True, serialize=False),
        ),
    ]
