# Generated by Django 5.1.3 on 2025-02-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_document_document_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.CharField(default='8118006274', max_length=16),
        ),
        migrations.AlterField(
            model_name='formdocument',
            name='form_id',
            field=models.CharField(default='8118006274', max_length=10, primary_key=True, serialize=False, verbose_name='Form ID'),
        ),
        migrations.AlterField(
            model_name='transmital',
            name='transmital_id',
            field=models.CharField(default='811800627470', max_length=16, primary_key=True, serialize=False),
        ),
    ]
