# Generated by Django 5.1.3 on 2025-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=962107508548, max_length=12),
        ),
    ]
