# Generated by Django 5.1.3 on 2024-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=823387234653, max_length=12),
        ),
    ]
