# Generated by Django 5.1.3 on 2024-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_survey_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=263380684770, max_length=12),
        ),
    ]
