# Generated by Django 5.1.3 on 2025-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_survey_survey_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=808067593234, max_length=12),
        ),
    ]
