# Generated by Django 5.1.3 on 2025-02-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_survey_question_alter_survey_survey_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='duration',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='trainer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=463851303977, max_length=12),
        ),
    ]
