# Generated by Django 5.1.3 on 2025-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_trainingprogram_duration_trainingprogram_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_id',
            field=models.CharField(default=356878007217, max_length=12),
        ),
    ]
